name: external_dependencies
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  go_router: ^14.1.4
  intl: ^0.19.0
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
