name: external_dependencies
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  fan_carousel_image_slider: ^1.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  intl: ^0.19.0
  path_provider: ^2.1.5
  photo_manager: ^3.6.3
  stack_trace: ^1.11.1
  http: ^1.2.2
  flutter_floating_bottom_bar: ^1.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
